// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/15/2024, 9:16:30 AM
const configMerger = require("C:/Users/Hacker/Desktop/telegramBot-vue/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/Hacker/Desktop/telegramBot-vue/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Hacker/Desktop/telegramBot-vue/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Hacker/Desktop/telegramBot-vue/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Hacker/Desktop/telegramBot-vue/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Hacker/Desktop/telegramBot-vue/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Hacker/Desktop/telegramBot-vue/plugins/**/*.{js,ts,mjs}","C:/Users/Hacker/Desktop/telegramBot-vue/composables/**/*.{js,ts,mjs}","C:/Users/Hacker/Desktop/telegramBot-vue/utils/**/*.{js,ts,mjs}","C:/Users/Hacker/Desktop/telegramBot-vue/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Hacker/Desktop/telegramBot-vue/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Hacker/Desktop/telegramBot-vue/app.config.{js,ts,mjs}"] }));

module.exports = config
