// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/15/2024, 3:08:42 PM
const configMerger = require("C:/Users/mchan/OneDrive/Desktop/dooggs/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/mchan/OneDrive/Desktop/dooggs/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mchan/OneDrive/Desktop/dooggs/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mchan/OneDrive/Desktop/dooggs/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mchan/OneDrive/Desktop/dooggs/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mchan/OneDrive/Desktop/dooggs/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mchan/OneDrive/Desktop/dooggs/plugins/**/*.{js,ts,mjs}","C:/Users/mchan/OneDrive/Desktop/dooggs/composables/**/*.{js,ts,mjs}","C:/Users/mchan/OneDrive/Desktop/dooggs/utils/**/*.{js,ts,mjs}","C:/Users/mchan/OneDrive/Desktop/dooggs/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mchan/OneDrive/Desktop/dooggs/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mchan/OneDrive/Desktop/dooggs/app.config.{js,ts,mjs}"] }));

module.exports = config
